### ISSUE TITLE
KiCad project grid mismatch

### ISSUE THREAD

**Issue by rogerdahl** [FPGAwars/icezum#38]
Apologies if this is not related to icezum. I'm using the icezum KiCad project to experiment with KiCad. When I open `icezum.kicad_pcb` in KiCad, the grid settings in KiCad do not update to match those used in the icezum project, so when I modify the design or add tracks, the modifications do not line up with the original design. I don't see why the grid spacing and origin wouldn't be included in the project, so I'm wondering if this is an issue with the icezum project? If there is no way to set them from the project, could you let me know what they are, so that I can set them manually?

**Comment by Obijuan** [comment]
The size is not stored in the project properties because is something that you change very often when designing the PCB.  I am showing to you some values you can use

* For the schematics:

![kicad-schematics-grid](https://cloud.githubusercontent.com/assets/1286062/24344531/38e12346-12cc-11e7-9767-faeb601b9b0a.png)

* For the PCB:

![kicad-pcb-grid](https://cloud.githubusercontent.com/assets/1286062/24344536/3f9d5d9e-12cc-11e7-8d30-5b75d7efbf37.png)
